### ISSUE TITLE
Begin writting even if an error is raised

### ISSUE THREAD

**Issue by toniodo** [Seb-sti1/ProjectHub#42]
A bracket is written in the .json file even if the writing fails (tested for projects.json). So the file only contains '[' and can't be opened again by the json module.

**Comment by clementlrd** [comment]
Thank you for this issue report! What causes an error to be triggered ? This can happen during development because the code we produce may contain errors, but it can also unexpectedly happen in production with an unknown error!

For me, the easiest way to do it is: when the `overwrite` field is set to `True`, we write the content in `[filepath].tmp` that we then rename to the original file. This way, if an error happen, the original file is not overwritten.

**Comment by toniodo** [comment]
Yes in my case it was an error in my code (serialization problem but nevermind). Sure! That would be a possible option. Is a  method that controls the possiblity of JSON serialization of the data before writting it possible?

**Comment by clementlrd** [comment]
Yes good idea ! It is possible to change the JSON encoder used, this is what you've done for the path in the pydantic object. But it is also possible to create an object to the serializer for the defaults in the io module that handle basic objects as Path!
